# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
