# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20171115_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='titulo',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
